import { GearItem } from "./types";

export const gearData: GearItem[] = [
  {
    id: "cam-1",
    item_name: "CANON EOS-M Magic Lantern OS w Cage and Rail Rig",
    category: "Cameras",
    quantity: 1,
    short_description: "Compact mirrorless with Magic Lantern firmware, cage and rail rig",
    daily_rate_php: 900,
    replacement_value_php: 20600,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "cam-2",
    item_name: "A7IV Fullframe Body W Rig (MatteBox, Vmount, Monitor, Rails, Cage)",
    category: "Cameras",
    quantity: 1,
    short_description: "Sony A7IV full-frame body with complete cinema rig setup",
    daily_rate_php: 2500,
    replacement_value_php: 129999,
    inclusions: "A7IV Cage, Quick Mount Mattebox, Rails, Focus Puller, On Cam Monitor",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "cam-3",
    item_name: "A7SII Fullframe Body W Rig (MatteBox, Vmount, Monitor, Rails, Cage)",
    category: "Cameras",
    quantity: 1,
    short_description: "Sony A7SII low-light beast with cinema rig package",
    daily_rate_php: 2000,
    replacement_value_php: 60000,
    inclusions: "A7SII Cage, Quick Mount Mattebox, Rails, Focus Puller, On Cam Monitor",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "lens-1",
    item_name: "Sony 24-105 F4",
    category: "Lenses",
    quantity: 1,
    short_description: "Versatile full-frame zoom lens with constant F4 aperture",
    daily_rate_php: 500,
    replacement_value_php: 25000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "lens-2",
    item_name: "Minolta 35mm F2.8",
    category: "Lenses",
    quantity: 1,
    short_description: "Classic vintage wide-angle prime lens",
    daily_rate_php: 350,
    replacement_value_php: 5300,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "lens-3",
    item_name: "Takumar Bayonet Mount 135mm F2.5",
    category: "Lenses",
    quantity: 1,
    short_description: "Legendary vintage telephoto with beautiful bokeh",
    daily_rate_php: 400,
    replacement_value_php: 5900,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "lens-4",
    item_name: "Helios 58mm F2.0",
    category: "Lenses",
    quantity: 1,
    short_description: "Soviet-era lens famous for swirly bokeh effect",
    daily_rate_php: 400,
    replacement_value_php: 2950,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "lens-5",
    item_name: "Vivitar 70-210mm F3.5",
    category: "Lenses",
    quantity: 1,
    short_description: "Versatile vintage telephoto zoom lens",
    daily_rate_php: 350,
    replacement_value_php: 3550,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "lens-6",
    item_name: "Nikon AF-S DX NIKKOR 18-105mm f/3.5-5.6G ED VR",
    category: "Lenses",
    quantity: 1,
    short_description: "Nikon all-purpose zoom with VR stabilization",
    daily_rate_php: 450,
    replacement_value_php: 7050,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "lens-7",
    item_name: "7Artisans 25mm F/1.8 MF Manual Focus APS-C EF-M",
    category: "Lenses",
    quantity: 1,
    short_description: "Fast wide-angle manual focus prime, 12mm FF equivalent with adapter",
    daily_rate_php: 350,
    replacement_value_php: 4350,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "lens-8",
    item_name: "Minolta MD Rokkor 50mm F/1.4",
    category: "Lenses",
    quantity: 1,
    short_description: "Fast vintage standard prime, excellent for portraits",
    daily_rate_php: 450,
    replacement_value_php: 7000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "lens-9",
    item_name: "K&F Nikon AI(G)- EF-M Lens Adapter",
    category: "Lenses",
    quantity: 1,
    short_description: "Nikon to EF-M mount adapter",
    daily_rate_php: null,
    replacement_value_php: 500,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "lens-10",
    item_name: "LightDow 0.45x Lens Converter + Macro",
    category: "Lenses",
    quantity: 1,
    short_description: "Wide-angle converter with macro capability",
    daily_rate_php: null,
    replacement_value_php: 600,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "lens-11",
    item_name: "LightDow 0.35x Lens Converter + Macro",
    category: "Lenses",
    quantity: 1,
    short_description: "Ultra wide-angle converter with macro capability",
    daily_rate_php: null,
    replacement_value_php: 800,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "mon-1",
    item_name: "7in Viltrox Field Monitor",
    category: "Monitors",
    quantity: 1,
    short_description: "7-inch on-camera field monitor",
    daily_rate_php: 400,
    replacement_value_php: 9000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "mon-2",
    item_name: "5.5in Feelworld F5 Pro Field Monitor",
    category: "Monitors",
    quantity: 1,
    short_description: "Compact 5.5-inch field monitor for on-camera use",
    daily_rate_php: 500,
    replacement_value_php: 9000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "mon-3",
    item_name: "6in FEELWORLD F5 PRO V4 Field Monitor",
    category: "Monitors",
    quantity: 1,
    short_description: "6-inch touchscreen field monitor with waveform",
    daily_rate_php: 600,
    replacement_value_php: 9000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "mon-4",
    item_name: "Vention HDMI 2.1 Cable Dolby Vision Ultra 8K@60Hz",
    category: "Monitors",
    quantity: 4,
    short_description: "Premium HDMI 2.1 cable supporting 8K resolution",
    daily_rate_php: 100,
    replacement_value_php: 229,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "mon-5",
    item_name: "Shimbol TP MINI Wireless Video Transmitter Receiver Kit (2RX, 2TX)",
    category: "Monitors",
    quantity: 2,
    short_description: "Wireless video transmission kit with 2 receivers and 2 transmitters",
    daily_rate_php: 500,
    replacement_value_php: 5250,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "fpr-1",
    item_name: "SmallRig Lite Focus Puller Rig",
    category: "Focus Puller Rig",
    quantity: 1,
    short_description: "Complete focus puller rig package with monitor, wireless follow focus, and accessories",
    daily_rate_php: 2500,
    replacement_value_php: 50000,
    inclusions: "5.5\" Feelworld F5 Pro Field Monitor, SmallRig Wireless Follow Focus Kit, SmallRig Side Handle 2772, NEEWER Monitor Mount, Canon Neck Strap, Nitze Monitor Cage, NPF Charger, NPF Battery, HDMI Cables",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "fpr-2",
    item_name: "5.5\" Feelworld F5 Pro Field Monitor",
    category: "Focus Puller Rig",
    quantity: 1,
    short_description: "Compact field monitor for focus pulling setups",
    daily_rate_php: 500,
    replacement_value_php: 8000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "fpr-3",
    item_name: "SmallRig Wireless Follow Focus Kit Wireless Receiver Motor",
    category: "Focus Puller Rig",
    quantity: 1,
    short_description: "Wireless follow focus system with receiver motor",
    daily_rate_php: 1100,
    replacement_value_php: 12000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "fpr-4",
    item_name: "SmallRig Lightweight Side Handle 2772",
    category: "Focus Puller Rig",
    quantity: 1,
    short_description: "Ergonomic side handle for camera rigs",
    daily_rate_php: null,
    replacement_value_php: 1450,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "fpr-5",
    item_name: "NEEWER Camera Monitor Mount with Cold Shoe, 1/4\" Screw",
    category: "Focus Puller Rig",
    quantity: 1,
    short_description: "Versatile monitor mount with cold shoe and 1/4\" thread",
    daily_rate_php: null,
    replacement_value_php: 600,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "fpr-6",
    item_name: "Canon Neck Strap",
    category: "Focus Puller Rig",
    quantity: 1,
    short_description: "Canon branded camera neck strap",
    daily_rate_php: null,
    replacement_value_php: 1200,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "fpr-7",
    item_name: "Nitze Monitor Cage for Feelworld",
    category: "Focus Puller Rig",
    quantity: 1,
    short_description: "Protective cage for Feelworld monitors",
    daily_rate_php: null,
    replacement_value_php: 2350,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "fpr-8",
    item_name: "NPF Charger, NPF Battery, HDMI Cables",
    category: "Focus Puller Rig",
    quantity: 1,
    short_description: "Power and connectivity accessories bundle",
    daily_rate_php: 400,
    replacement_value_php: 2350,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-1",
    item_name: "V Mount CITYORK BP-222W / BP-185W",
    category: "Accessories",
    quantity: 2,
    short_description: "High-capacity V-mount batteries for cinema rigs",
    daily_rate_php: 300,
    replacement_value_php: 5000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-2",
    item_name: "LPE12 Dummy Battery USB3 to DC Jack",
    category: "Accessories",
    quantity: 1,
    short_description: "Continuous power solution for Canon EOS-M cameras",
    daily_rate_php: null,
    replacement_value_php: 1200,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-3",
    item_name: "Assorted HDMI Cables (Standard, Micro, Mini)",
    category: "Accessories",
    quantity: 6,
    short_description: "HDMI cable set in Standard, Micro, and Mini sizes",
    daily_rate_php: null,
    replacement_value_php: 600,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-4",
    item_name: "3.5mm Monitor Mount + SmallRig Super Clamp with 1/4' Ball Head",
    category: "Accessories",
    quantity: 1,
    short_description: "Monitor mounting solution with ball head adjustment",
    daily_rate_php: 100,
    replacement_value_php: 1750,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-5",
    item_name: "4 Slot NPF Charging Dock",
    category: "Accessories",
    quantity: 1,
    short_description: "Quad-slot NPF battery charging dock",
    daily_rate_php: 150,
    replacement_value_php: 2950,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-6",
    item_name: "LPE12 Charging Dock",
    category: "Accessories",
    quantity: 2,
    short_description: "Dual charger for Canon LP-E12 batteries",
    daily_rate_php: 100,
    replacement_value_php: 1450,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-7",
    item_name: "Jeebel NP-F970 7800mAh",
    category: "Accessories",
    quantity: 3,
    short_description: "High-capacity NP-F970 battery, 7800mAh",
    daily_rate_php: 600,
    replacement_value_php: 1250,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-8",
    item_name: "ZGCINE NP-F Battery Adapter Plate Multi Use NPF Fast Charger QC3.0/PD3.0",
    category: "Accessories",
    quantity: 2,
    short_description: "Multi-use NPF adapter with fast charge QC3.0/PD3.0",
    daily_rate_php: 250,
    replacement_value_php: 2950,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-9",
    item_name: "NPF-770",
    category: "Accessories",
    quantity: 2,
    short_description: "Standard NPF-770 rechargeable battery",
    daily_rate_php: 100,
    replacement_value_php: 1200,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-10",
    item_name: "Sony NPF-970",
    category: "Accessories",
    quantity: 2,
    short_description: "Genuine Sony NPF-970 high-capacity battery",
    daily_rate_php: 150,
    replacement_value_php: 12000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-11",
    item_name: "Zhiyun Weebil Lab S Gimbal",
    category: "Accessories",
    quantity: 1,
    short_description: "3-axis stabilizer for mirrorless and DSLR cameras",
    daily_rate_php: 600,
    replacement_value_php: 15250,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-12",
    item_name: "DJI RS4 Combo",
    category: "Accessories",
    quantity: 1,
    short_description: "Professional 3-axis gimbal stabilizer combo kit",
    daily_rate_php: 1500,
    replacement_value_php: 20000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-13",
    item_name: "FotoPro Fluid Head Tripod",
    category: "Accessories",
    quantity: 1,
    short_description: "Professional fluid head video tripod",
    daily_rate_php: 300,
    replacement_value_php: 7050,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-14",
    item_name: "NEEWER PG002 Mini Matte Box with 4\"x5.65\" Filter Tray",
    category: "Accessories",
    quantity: 1,
    short_description: "Compact matte box with filter tray and 4 lens ring adapters",
    daily_rate_php: 200,
    replacement_value_php: 4000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-15",
    item_name: "ZOMEI Series Lens Filters ND2 ~ ND400",
    category: "Accessories",
    quantity: 1,
    short_description: "Variable ND filter set from ND2 to ND400",
    daily_rate_php: 100,
    replacement_value_php: 1500,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-16",
    item_name: "Andoer ND Variable Filter 67mm",
    category: "Accessories",
    quantity: 1,
    short_description: "67mm variable neutral density filter",
    daily_rate_php: 50,
    replacement_value_php: 1450,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-17",
    item_name: "Step Rings Assorted (43mm-77mm)",
    category: "Accessories",
    quantity: 1,
    short_description: "Full set of step-up rings from 43mm to 77mm",
    daily_rate_php: 100,
    replacement_value_php: 500,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-18",
    item_name: "Lenovo Thinkplus USB Card Reader USB 3.0 3-in-1 SD/TF/CF",
    category: "Accessories",
    quantity: 1,
    short_description: "High-speed USB 3.0 multi-format card reader",
    daily_rate_php: 100,
    replacement_value_php: 600,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-19",
    item_name: "Lexar LRW515U CFexpress Type A USB-C Card Reader",
    category: "Accessories",
    quantity: 1,
    short_description: "CFexpress Type A reader for Sony cameras",
    daily_rate_php: 250,
    replacement_value_php: 2500,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-20",
    item_name: "128 GB SD EXTREME PRO V30",
    category: "Accessories",
    quantity: 2,
    short_description: "SanDisk 128GB UHS-I V30 memory card",
    daily_rate_php: 150,
    replacement_value_php: 2000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-21",
    item_name: "64 GB SD EXTREME PRO V30",
    category: "Accessories",
    quantity: 2,
    short_description: "SanDisk 64GB UHS-I V30 memory card",
    daily_rate_php: 250,
    replacement_value_php: 1500,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-22",
    item_name: "128GB LEXAR SILVER PRO V60",
    category: "Accessories",
    quantity: 1,
    short_description: "Lexar Silver Pro 128GB V60 SD card",
    daily_rate_php: 250,
    replacement_value_php: 2350,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-23",
    item_name: "64GB TOUGH-G Series V90",
    category: "Accessories",
    quantity: 1,
    short_description: "Sony TOUGH-G 64GB V90 ultra-durable memory card",
    daily_rate_php: 450,
    replacement_value_php: 4700,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "acc-24",
    item_name: "800W Redhead Tungsten 3200K w Barndoor",
    category: "Accessories",
    quantity: 1,
    short_description: "Classic 800W tungsten redhead light with barndoor",
    daily_rate_php: 500,
    replacement_value_php: 5000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "light-1",
    item_name: "650W CameTV Fresnel Tungsten 3200K",
    category: "Lights",
    quantity: 1,
    short_description: "Professional 650W Fresnel tungsten light",
    daily_rate_php: 700,
    replacement_value_php: 11800,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "light-2",
    item_name: "Godox Litemons LE600BI Bi-Color 610W LED Studio COB Light",
    category: "Lights",
    quantity: 1,
    short_description: "610W bi-color LED COB light with Bowens mount and wireless app control",
    daily_rate_php: 2000,
    replacement_value_php: 29450,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "light-3",
    item_name: "200W Sidande COB Bi-Color 2500K-6500K w/ Wireless App",
    category: "Lights",
    quantity: 3,
    short_description: "200W bi-color COB light with softbox and light stand",
    daily_rate_php: 800,
    replacement_value_php: 8000,
    inclusions: "200W COB, Softbox, Baby Lightstand Steel",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "light-4",
    item_name: "65W Ulanzi L024 COB RGB Bi-Color w Dish 2400K-5600K",
    category: "Lights",
    quantity: 1,
    short_description: "Compact RGB bi-color COB light with dish reflector",
    daily_rate_php: 500,
    replacement_value_php: 5850,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "light-5",
    item_name: "100W Merlin HPL50 7500K w Barndoor",
    category: "Lights",
    quantity: 1,
    short_description: "100W daylight-balanced LED with barndoor",
    daily_rate_php: 400,
    replacement_value_php: 11800,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "light-6",
    item_name: "COLBOR PL5 Bicolor Rechargeable Mini Panel 2400K-10000K",
    category: "Lights",
    quantity: 1,
    short_description: "Pocket-size bi-color LED panel, rechargeable",
    daily_rate_php: 300,
    replacement_value_php: 2500,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "diff-1",
    item_name: "6 by 6 ft Aluminum Alloy Butterfly Kit",
    category: "Diffusion & Support",
    quantity: 1,
    short_description: "Complete 6x6ft butterfly kit with frame, diffusion silk, C-stand, and grip",
    daily_rate_php: 2000,
    replacement_value_php: 20000,
    inclusions: "6x6ft Aluminum Frame, 6x6ft Diffusion Silk, C Stand, Grip Head, Allen Wrenches",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "diff-2",
    item_name: "6 by 6 ft Aluminum Alloy Frame (Butterfly)",
    category: "Diffusion & Support",
    quantity: 1,
    short_description: "6x6ft aluminum butterfly frame only",
    daily_rate_php: null,
    replacement_value_php: 11800,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "diff-3",
    item_name: "6 by 6 ft Diffusion Silk (Butterfly)",
    category: "Diffusion & Support",
    quantity: 1,
    short_description: "6x6ft diffusion silk for butterfly frame",
    daily_rate_php: null,
    replacement_value_php: 2950,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "diff-4",
    item_name: "C Stand (Butterfly)",
    category: "Diffusion & Support",
    quantity: 2,
    short_description: "Heavy-duty C-stand for butterfly frames",
    daily_rate_php: null,
    replacement_value_php: 8850,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "diff-5",
    item_name: "Grip Head (Butterfly)",
    category: "Diffusion & Support",
    quantity: 2,
    short_description: "Grip head for butterfly support systems",
    daily_rate_php: null,
    replacement_value_php: 1450,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "diff-6",
    item_name: "Allen Wrenches (Butterfly)",
    category: "Diffusion & Support",
    quantity: 1,
    short_description: "Allen wrench set for butterfly frame assembly",
    daily_rate_php: null,
    replacement_value_php: 600,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "diff-7",
    item_name: "AMBITFUL QS65 (65cm With Grid)",
    category: "Diffusion & Support",
    quantity: 1,
    short_description: "65cm quick-setup softbox with grid",
    daily_rate_php: 300,
    replacement_value_php: 3000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "mod-1",
    item_name: "AMBITFUL Softbox 60x90cm Bowens Mount + Grid",
    category: "Modifiers",
    quantity: 1,
    short_description: "60x90cm softbox with Bowens mount and grid",
    daily_rate_php: 200,
    replacement_value_php: 2000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "mod-2",
    item_name: "Lantern Softbox Bowens Mount",
    category: "Modifiers",
    quantity: 1,
    short_description: "Lantern-style softbox with Bowens mount for 360° soft light",
    daily_rate_php: 200,
    replacement_value_php: 2000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "mod-3",
    item_name: "NICEFOTO Parabolic Softbox 120CM Bowens with Grid",
    category: "Modifiers",
    quantity: 1,
    short_description: "Large 120cm parabolic softbox with grid for dramatic lighting",
    daily_rate_php: 400,
    replacement_value_php: 6500,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "diff-8",
    item_name: "Steel Grip Head",
    category: "Diffusion & Support",
    quantity: 6,
    short_description: "Heavy-duty steel grip head for flags and frames",
    daily_rate_php: 200,
    replacement_value_php: 6000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "mod-4",
    item_name: "Selens Stainless Flag Panel (75x90cm)",
    category: "Modifiers",
    quantity: 1,
    short_description: "75x90cm stainless steel flag panel for light control",
    daily_rate_php: 250,
    replacement_value_php: 4100,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-1",
    item_name: "Black Styro Board 1.5 x 1m",
    category: "Misc",
    quantity: 1,
    short_description: "Black styrofoam board for negative fill",
    daily_rate_php: null,
    replacement_value_php: 600,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-2",
    item_name: "Reflector Set 5 in 1 (Large, Medium, Small)",
    category: "Misc",
    quantity: 3,
    short_description: "5-in-1 reflector set in multiple sizes",
    daily_rate_php: 200,
    replacement_value_php: 1750,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-3",
    item_name: "Telescopic and Standard Steel Boom Pole (50cm-250cm) with C-stand Grip Head",
    category: "Misc",
    quantity: 3,
    short_description: "Adjustable boom pole with C-stand grip head",
    daily_rate_php: 200,
    replacement_value_php: 2000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-4",
    item_name: "Mini Backdrop A Clip",
    category: "Misc",
    quantity: 8,
    short_description: "Small backdrop clamp clips",
    daily_rate_php: null,
    replacement_value_php: 300,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-5",
    item_name: "Negative Black Muslin (No Frame) 3 x 5m",
    category: "Misc",
    quantity: 1,
    short_description: "3x5m black muslin backdrop for negative fill",
    daily_rate_php: 200,
    replacement_value_php: 2950,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-6",
    item_name: "2\" Metal Clips",
    category: "Misc",
    quantity: 25,
    short_description: "Heavy-duty 2-inch metal spring clips",
    daily_rate_php: 200,
    replacement_value_php: 50,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-7",
    item_name: "SmallRig Universal Magic Arm with Dual Ball Heads (3in, 1/4-20) 2157",
    category: "Misc",
    quantity: 2,
    short_description: "Articulating magic arm with dual ball heads",
    daily_rate_php: 350,
    replacement_value_php: 1750,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-8",
    item_name: "Flexible Super Clamp Double Crab Clamps 360° Rotatable",
    category: "Misc",
    quantity: 1,
    short_description: "360° rotatable double crab clamp",
    daily_rate_php: 100,
    replacement_value_php: 1200,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-9",
    item_name: "SmallRig Multi-Functional Crab-Shaped Clamp with Ballhead Magic Arm 2164",
    category: "Misc",
    quantity: 1,
    short_description: "Multi-functional crab clamp with ballhead magic arm",
    daily_rate_php: null,
    replacement_value_php: 2050,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-10",
    item_name: "Mini Backdrop Clip",
    category: "Misc",
    quantity: 8,
    short_description: "Compact backdrop clips",
    daily_rate_php: null,
    replacement_value_php: 250,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-11",
    item_name: "3.3M C-Stand + 1.2m Detachable Arm",
    category: "Misc",
    quantity: 2,
    short_description: "3.3m C-stand with detachable 1.2m extension arm",
    daily_rate_php: 400,
    replacement_value_php: 8850,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-12",
    item_name: "Ambitiful Lightstands Stainless Steel (280cm)",
    category: "Misc",
    quantity: 4,
    short_description: "280cm stainless steel light stands",
    daily_rate_php: 250,
    replacement_value_php: 4700,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-13",
    item_name: "Lightstands Steel Alloy (Mixed Heights)",
    category: "Misc",
    quantity: 8,
    short_description: "Steel alloy light stands in assorted heights",
    daily_rate_php: 180,
    replacement_value_php: 2950,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-14",
    item_name: "Green Screen 5 x 5m",
    category: "Misc",
    quantity: 1,
    short_description: "5x5m chroma key green screen backdrop",
    daily_rate_php: 400,
    replacement_value_php: 4700,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-15",
    item_name: "Selens Diffusion Fabric Nylon Silk White 4 x 1.7m",
    category: "Misc",
    quantity: 2,
    short_description: "White nylon silk diffusion fabric for soft lighting",
    daily_rate_php: 400,
    replacement_value_php: 2950,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-16",
    item_name: "Unbleached Muslin (No Frame) 1.6 x 6m",
    category: "Misc",
    quantity: 1,
    short_description: "Natural unbleached muslin backdrop",
    daily_rate_php: 500,
    replacement_value_php: 2350,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-17",
    item_name: "300W and 900W Fog Machine",
    category: "Misc",
    quantity: 2,
    short_description: "Fog machines in 300W and 900W for atmospheric effects",
    daily_rate_php: 800,
    replacement_value_php: 5300,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-18",
    item_name: "5L Fog Liquid",
    category: "Misc",
    quantity: 1,
    short_description: "5-liter fog machine liquid refill",
    daily_rate_php: 200,
    replacement_value_php: 1450,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-19",
    item_name: "Extension Cord 5M",
    category: "Misc",
    quantity: 6,
    short_description: "5-meter power extension cord",
    daily_rate_php: 50,
    replacement_value_php: 600,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-20",
    item_name: "Extension Hub 10 Slots",
    category: "Misc",
    quantity: 1,
    short_description: "10-slot power extension hub",
    daily_rate_php: 200,
    replacement_value_php: 1200,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-21",
    item_name: "Radio Baofeng 888S",
    category: "Misc",
    quantity: 4,
    short_description: "Two-way radio for on-set communication",
    daily_rate_php: 150,
    replacement_value_php: 1200,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "misc-22",
    item_name: "Sandbags (4kg)",
    category: "Misc",
    quantity: 6,
    short_description: "4kg sandbags for securing stands and rigs",
    daily_rate_php: 100,
    replacement_value_php: 300,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "sound-1",
    item_name: "H6 Zoom Recorder",
    category: "Sound",
    quantity: 1,
    short_description: "6-track portable recorder for professional field recording",
    daily_rate_php: 600,
    replacement_value_php: 1450,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "sound-2",
    item_name: "Sony MDR-7506 Headphones",
    category: "Sound",
    quantity: 1,
    short_description: "Industry-standard professional monitoring headphones",
    daily_rate_php: 300,
    replacement_value_php: 600,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "sound-3",
    item_name: "Sennheiser MKE 600 Boom Mic",
    category: "Sound",
    quantity: 1,
    short_description: "Professional shotgun microphone for film and broadcast",
    daily_rate_php: 1500,
    replacement_value_php: 1200,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "sound-4",
    item_name: "50 ft M/F Wire XLR",
    category: "Sound",
    quantity: 1,
    short_description: "50-foot XLR cable for professional audio connections",
    daily_rate_php: 100,
    replacement_value_php: 1200,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
  {
    id: "sound-5",
    item_name: "Andoer Boom Pole 155cm",
    category: "Sound",
    quantity: 1,
    short_description: "155cm boom pole for overhead microphone positioning",
    daily_rate_php: 100,
    replacement_value_php: 2000,
    inclusions: "",
    status: "Available",
    notes: "",
    image_url: "/placeholder.svg",
  },
];
